/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as ListRouteImport } from './routes/list'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DishNewRouteImport } from './routes/dish.new'
import { Route as DishIdRouteImport } from './routes/dish.$id'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DishNewRoute = DishNewRouteImport.update({
  id: '/dish/new',
  path: '/dish/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DishIdRoute = DishIdRouteImport.update({
  id: '/dish/$id',
  path: '/dish/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingredients': typeof IngredientsRoute
  '/list': typeof ListRoute
  '/stores': typeof StoresRoute
  '/dish/$id': typeof DishIdRoute
  '/dish/new': typeof DishNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingredients': typeof IngredientsRoute
  '/list': typeof ListRoute
  '/stores': typeof StoresRoute
  '/dish/$id': typeof DishIdRoute
  '/dish/new': typeof DishNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingredients': typeof IngredientsRoute
  '/list': typeof ListRoute
  '/stores': typeof StoresRoute
  '/dish/$id': typeof DishIdRoute
  '/dish/new': typeof DishNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ingredients'
    | '/list'
    | '/stores'
    | '/dish/$id'
    | '/dish/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ingredients' | '/list' | '/stores' | '/dish/$id' | '/dish/new'
  id:
    | '__root__'
    | '/'
    | '/ingredients'
    | '/list'
    | '/stores'
    | '/dish/$id'
    | '/dish/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngredientsRoute: typeof IngredientsRoute
  ListRoute: typeof ListRoute
  StoresRoute: typeof StoresRoute
  DishIdRoute: typeof DishIdRoute
  DishNewRoute: typeof DishNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dish/new': {
      id: '/dish/new'
      path: '/dish/new'
      fullPath: '/dish/new'
      preLoaderRoute: typeof DishNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dish/$id': {
      id: '/dish/$id'
      path: '/dish/$id'
      fullPath: '/dish/$id'
      preLoaderRoute: typeof DishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngredientsRoute: IngredientsRoute,
  ListRoute: ListRoute,
  StoresRoute: StoresRoute,
  DishIdRoute: DishIdRoute,
  DishNewRoute: DishNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
