/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileIdRouteImport } from './routes/$profileId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIdIndexRouteImport } from './routes/$profileId/index'
import { Route as ProfileIdStoresRouteImport } from './routes/$profileId/stores'
import { Route as ProfileIdIngredientsRouteImport } from './routes/$profileId/ingredients'
import { Route as ProfileIdDishesRouteImport } from './routes/$profileId/dishes'
import { Route as ProfileIdDishNewRouteImport } from './routes/$profileId/dish.new'
import { Route as ProfileIdDishIdRouteImport } from './routes/$profileId/dish.$id'

const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdIndexRoute = ProfileIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileIdRoute,
} as any)
const ProfileIdStoresRoute = ProfileIdStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => ProfileIdRoute,
} as any)
const ProfileIdIngredientsRoute = ProfileIdIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => ProfileIdRoute,
} as any)
const ProfileIdDishesRoute = ProfileIdDishesRouteImport.update({
  id: '/dishes',
  path: '/dishes',
  getParentRoute: () => ProfileIdRoute,
} as any)
const ProfileIdDishNewRoute = ProfileIdDishNewRouteImport.update({
  id: '/dish/new',
  path: '/dish/new',
  getParentRoute: () => ProfileIdRoute,
} as any)
const ProfileIdDishIdRoute = ProfileIdDishIdRouteImport.update({
  id: '/dish/$id',
  path: '/dish/$id',
  getParentRoute: () => ProfileIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$profileId': typeof ProfileIdRouteWithChildren
  '/$profileId/dishes': typeof ProfileIdDishesRoute
  '/$profileId/ingredients': typeof ProfileIdIngredientsRoute
  '/$profileId/stores': typeof ProfileIdStoresRoute
  '/$profileId/': typeof ProfileIdIndexRoute
  '/$profileId/dish/$id': typeof ProfileIdDishIdRoute
  '/$profileId/dish/new': typeof ProfileIdDishNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$profileId/dishes': typeof ProfileIdDishesRoute
  '/$profileId/ingredients': typeof ProfileIdIngredientsRoute
  '/$profileId/stores': typeof ProfileIdStoresRoute
  '/$profileId': typeof ProfileIdIndexRoute
  '/$profileId/dish/$id': typeof ProfileIdDishIdRoute
  '/$profileId/dish/new': typeof ProfileIdDishNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$profileId': typeof ProfileIdRouteWithChildren
  '/$profileId/dishes': typeof ProfileIdDishesRoute
  '/$profileId/ingredients': typeof ProfileIdIngredientsRoute
  '/$profileId/stores': typeof ProfileIdStoresRoute
  '/$profileId/': typeof ProfileIdIndexRoute
  '/$profileId/dish/$id': typeof ProfileIdDishIdRoute
  '/$profileId/dish/new': typeof ProfileIdDishNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$profileId'
    | '/$profileId/dishes'
    | '/$profileId/ingredients'
    | '/$profileId/stores'
    | '/$profileId/'
    | '/$profileId/dish/$id'
    | '/$profileId/dish/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$profileId/dishes'
    | '/$profileId/ingredients'
    | '/$profileId/stores'
    | '/$profileId'
    | '/$profileId/dish/$id'
    | '/$profileId/dish/new'
  id:
    | '__root__'
    | '/'
    | '/$profileId'
    | '/$profileId/dishes'
    | '/$profileId/ingredients'
    | '/$profileId/stores'
    | '/$profileId/'
    | '/$profileId/dish/$id'
    | '/$profileId/dish/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileIdRoute: typeof ProfileIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$profileId': {
      id: '/$profileId'
      path: '/$profileId'
      fullPath: '/$profileId'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$profileId/': {
      id: '/$profileId/'
      path: '/'
      fullPath: '/$profileId/'
      preLoaderRoute: typeof ProfileIdIndexRouteImport
      parentRoute: typeof ProfileIdRoute
    }
    '/$profileId/stores': {
      id: '/$profileId/stores'
      path: '/stores'
      fullPath: '/$profileId/stores'
      preLoaderRoute: typeof ProfileIdStoresRouteImport
      parentRoute: typeof ProfileIdRoute
    }
    '/$profileId/ingredients': {
      id: '/$profileId/ingredients'
      path: '/ingredients'
      fullPath: '/$profileId/ingredients'
      preLoaderRoute: typeof ProfileIdIngredientsRouteImport
      parentRoute: typeof ProfileIdRoute
    }
    '/$profileId/dishes': {
      id: '/$profileId/dishes'
      path: '/dishes'
      fullPath: '/$profileId/dishes'
      preLoaderRoute: typeof ProfileIdDishesRouteImport
      parentRoute: typeof ProfileIdRoute
    }
    '/$profileId/dish/new': {
      id: '/$profileId/dish/new'
      path: '/dish/new'
      fullPath: '/$profileId/dish/new'
      preLoaderRoute: typeof ProfileIdDishNewRouteImport
      parentRoute: typeof ProfileIdRoute
    }
    '/$profileId/dish/$id': {
      id: '/$profileId/dish/$id'
      path: '/dish/$id'
      fullPath: '/$profileId/dish/$id'
      preLoaderRoute: typeof ProfileIdDishIdRouteImport
      parentRoute: typeof ProfileIdRoute
    }
  }
}

interface ProfileIdRouteChildren {
  ProfileIdDishesRoute: typeof ProfileIdDishesRoute
  ProfileIdIngredientsRoute: typeof ProfileIdIngredientsRoute
  ProfileIdStoresRoute: typeof ProfileIdStoresRoute
  ProfileIdIndexRoute: typeof ProfileIdIndexRoute
  ProfileIdDishIdRoute: typeof ProfileIdDishIdRoute
  ProfileIdDishNewRoute: typeof ProfileIdDishNewRoute
}

const ProfileIdRouteChildren: ProfileIdRouteChildren = {
  ProfileIdDishesRoute: ProfileIdDishesRoute,
  ProfileIdIngredientsRoute: ProfileIdIngredientsRoute,
  ProfileIdStoresRoute: ProfileIdStoresRoute,
  ProfileIdIndexRoute: ProfileIdIndexRoute,
  ProfileIdDishIdRoute: ProfileIdDishIdRoute,
  ProfileIdDishNewRoute: ProfileIdDishNewRoute,
}

const ProfileIdRouteWithChildren = ProfileIdRoute._addFileChildren(
  ProfileIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileIdRoute: ProfileIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
